export const navLinks = [
  {
    id: 1,
    name: "Home",
    href: "#home",
  },
  {
    id: 2,
    name: "Gallery",
    href: "#gallery",
  },
  {
    id: 3,
    name: "About us",
    href: "#about",
  },
  {
    id: 4,
    name: "Contact us",
    href: "#contact",
  },
  {
    id: 5,
    name: "Testimonial",
    href: "#testimonial",
  },
];
export const popularCars = [
  {
    id: 1,
    name: "Koenigsegg",
    image: "./p-1.png",
    price: "₦650,000",
    period: "/day",
    gasoline: "90L",
    transmission: "Manual",
    capacity: "2 People",
    color: "lightblue", // Added color
  },
  {
    id: 2,
    name: "Nissan GT - R",
    image: "./p-2.png",
    price: "₦460,000",
    period: "/day",
    gasoline: "80L",
    transmission: "Manual",
    capacity: "2 People",
    color: "lightgreen", // Added color
  },
  {
    id: 3,
    name: "Rolls - Royce",
    image: "./p-3.png",
    price: "$660,000",
    period: "/day",
    gasoline: "70L",
    transmission: "Manual",
    capacity: "4 People",
    color: "lightyellow", // Added color
  },
];

export const rentalCars = [
  {
    id: 1,
    name: "Lamborghini Aventador",
    price: "₦720,000",
    originalPrice: "$800,000",
    image: "./r-1.png",
    gasoline: "70L",
    transmission: "Manual",
    capacity: "2 People",
    favorite: true,
  },
  {
    id: 2,
    name: "Rolls Royce Spectre",
    price: "₦850,000",
    image: "./r-2.png",
    gasoline: "80L",
    transmission: "Automatic",
    capacity: "2 People",
    favorite: false,
  },
  {
    id: 3,
    name: "BMW i8",
    price: "₦560,000",
    image: "./r-3.png",
    gasoline: "90L",
    transmission: "Manual",
    capacity: "2 People",
    favorite: true,
  },
  {
    id: 4,
    name: "Mercedes Benz S63 AMG 2023",
    price: "₦790,000",
    image: "./r-4.png",
    gasoline: "80L",
    transmission: "Automatic",
    capacity: "4 People",
    favorite: false,
  },
  {
    id: 5,
    name: "2025 Toyota Sequoia",
    price: "₦400,000",
    originalPrice: "₦600,000",
    image: "./r-5.png",
    gasoline: "70L",
    transmission: "Electric",
    capacity: "4 People",
    favorite: true,
  },
  {
    id: 6,
    name: "2017 Volkswagen Arteon",
    price: "₦550,000",
    image: "./r-6.png",
    gasoline: "80L",
    transmission: "Manual",
    capacity: "6 People",
    favorite: false,
  },
  {
    id: 7,
    name: "2025 Mitsubishi Outlander",
    price: "₦450,000",
    image: "./r-7.png",
    gasoline: "90L",
    transmission: "Manual",
    capacity: "4 People",
    favorite: true,
  },
  {
    id: 8,
    name: "Porsche 911 Carrera",
    price: "₦650,000",
    image: "./r-8.png",
    gasoline: "80L",
    transmission: "Manual",
    capacity: "2 People",
    favorite: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Akpan John",
    location: "Abuja, F.C.T",
    rating: 5,
    text: "AutoFlex made my business trip so much easier! The booking process was seamless, and the car was spotless. I'll definitely be using them again for all my rental needs.",
    avatar: "./t1.jpg",
    carType: "BMW 3 Series",
  },
  {
    id: 2,
    name: "Essien Eze",
    location: "Akwa Ibom",
    rating: 5,
    text: "Outstanding service from start to finish. The premium selection is impressive, and the staff went above and beyond to ensure I had the perfect vehicle for my weekend getaway.",
    avatar: "./t2.jpg",
    carType: "Mercedes-Benz C-Class",
  },
  {
    id: 3,
    name: "Emily Chiamaka",
    location: "Ikorodu, Lagos",
    rating: 5,
    text: "I was amazed by how quick and easy the pickup process was. The app is incredibly user-friendly, and the 24/7 support gave me peace of mind during my road trip.",
    avatar: "./t3.jpg",
    carType: "Tesla Model 3",
  },
  {
    id: 4,
    name: "David Joy",
    location: "Jimeta, Adamawa",
    rating: 5,
    text: "AutoFlex has completely changed how I think about car rentals. The flexibility, quality, and customer service are unmatched. Highly recommend to anyone looking for reliability.",
    avatar: "./t4.jpg",
    carType: "Audi A4",
  },
];
